### ISSUE TITLE
commit Bug

### ISSUE THREAD

**Issue by fredsun** [s13524801/android-fresco-blur#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.blur-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.blur-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libblur.so"

第一次发issue，感觉咱俩还是中文吧，好像缺少了arm64的so文件？。。

**Comment by s13524801** [comment]
更新 fresco 版本，内部已实现 BlurPostProcessor
